# Generated by Django 5.2.3 on 2025-07-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
        migrations.AddField(
            model_name='issue',
            name='type_temp',
            field=models.ManyToManyField(related_name='issues_temp', to='issues.type', verbose_name='Тип (новый)'),
        ),
    ]
